{{- if .Values.isManagement }}
{{- $chartVersion := .Chart.Version | replace "." "-" }}
{{- $mcsConfigs := list }}

{{- if .Values.managementCluster.includeInMesh }}
{{- $mcsConfigs = append $mcsConfigs (dict
    "name" (printf "%s-gateway-mgmt" .Chart.Name)
    "selfManagement" true
    "networkGateway" .Values.global.network
) }}
{{- end }}

{{- $mcsConfigs = append $mcsConfigs (dict
    "name" (printf "%s-gateway" .Chart.Name)
    "selfManagement" false
    "networkGateway" "{{ .Cluster.metadata.name }}-network"
    "waypointGateway" "{{ .Cluster.metadata.name }}-waypoint"
) }}

{{- range $cfg := $mcsConfigs }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ $cfg.name }}
spec:
  clusterSelector:
    matchLabels:
    {{- if $cfg.selfManagement }}
      k0rdent.mirantis.com/management-cluster: "true"
      # Workaround for https://github.com/k0rdent/kcm/issues/2610
    {{- else }}
      k0rdent.mirantis.com/istio-gateway: "true"
    {{- end }}
  dependsOn:
    - {{ $.Chart.Name }}-network
  serviceSpec:
  {{- if $cfg.selfManagement }}
    provider:
      selfManagement: true
  {{- end }}
    services:
      - name: istio-gateways
        namespace: {{ $.Release.Namespace }}
        template: {{ $.Chart.Name }}-propagation-{{ $chartVersion }}
        values: |
          {{`{{- $mesh := (index .Cluster.metadata.labels "k0rdent.mirantis.com/istio-mesh") -}}`}}
          {{`{{- $isregionalCluster := and .Cluster.metadata.labels (eq (index .Cluster.metadata.labels "k0rdent.mirantis.com/kcm-region-cluster") "true") }}`}}
          propagation:
            enabled: true
            data: |
              {{`{{ if $isregionalCluster }}`}}
              apiVersion: gateway.networking.k8s.io/v1
              kind: Gateway
              metadata:
                name: istio-ingressgateway
                namespace: istio-system
                annotations:
                  networking.istio.io/service-type: LoadBalancer
                  cert-manager.io/cluster-issuer: letsencrypt-exalsius-wildcard-dns-records
              spec:
                gatewayClassName: istio
                listeners:
                - name: http
                  port: 80
                  protocol: HTTP
                  allowedRoutes:
                    namespaces:
                      from: All
                - name: https-wildcard-{{`{{ $mesh }}`}}-ex-ls
                  protocol: HTTPS
                  port: 443
                  hostname: "*.{{`{{ $mesh }}`}}.ex.ls"
                  allowedRoutes:
                    namespaces:
                      from: All
                  tls:
                    mode: Terminate
                    certificateRefs:
                      - name: wildcard-{{`{{ $mesh }}`}}-ex-ls-tls
              ---
              {{`{{ end }}`}}
              apiVersion: gateway.networking.k8s.io/v1
              kind: Gateway
              metadata:
                name: istio-eastwestgateway
                namespace: istio-system
                annotations:
                  {{`{{ if $isregionalCluster }}`}}
                  networking.istio.io/service-type: LoadBalancer
                  {{`{{ else }}`}}
                  networking.istio.io/service-type: NodePort
                  traffic.istio.io/nodeSelector: kubernetes.io/os=linux
                  {{`{{ end }}`}}
                labels:
                  topology.istio.io/network: {{ $cfg.networkGateway }}
              spec:
                gatewayClassName: istio-east-west
                listeners:
                - name: mesh
                  port: 15008
                  protocol: HBONE
                  tls:
                    mode: Terminate
                    options:
                      gateway.istio.io/tls-terminate-mode: ISTIO_MUTUAL
              ---
              apiVersion: gateway.networking.k8s.io/v1
              kind: Gateway
              metadata:
                name: {{ $cfg.waypointGateway }}
                namespace: istio-system
                annotations:
                  networking.istio.io/service-type: ClusterIP
              spec:
                gatewayClassName: istio-waypoint
                listeners:
                - name: mesh
                  port: 15008
                  protocol: HBONE
                  allowedRoutes:
                    namespaces:
                      from: All
{{- end }}
{{- end }}
