{{- if .Values.isManagement }}
{{- $version := .Chart.Version | replace "." "-" }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: {{ .Chart.Name }}-{{ $version }}
  namespace: {{ .Values.kcm.namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: ./charts/k0rdent-istio
      version: {{ $.Chart.Version | quote }}
      sourceRef:
        kind: GitRepository
        name: k0rdent-istio
{{- end }}